---
- name: enabling access 
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: Copy checkbox job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/checkbox_jenkins_jobs.yml"
    dest: ~/jobs/checkbox_jenkins_jobs.yml

- name: Copy iTrust job script
  template:
    src: "{{ project_directory }}/roles/create_jobs/templates/iTrust_jenkins_jobs.yml"
    dest: ~/jobs/iTrust_jenkins_jobs.yml
  ignore_errors: true

- name: create jobs
  shell: 'cd  && jenkins-jobs --conf ~/jenkins_jobs.ini update ~/jobs'

